### ISSUE TITLE
Mistakes were made

### ISSUE THREAD

**Issue by Sandalot** [lordfido/pokemon-lets-guide#1]
https://github.com/lordfido/pokemon-lets-guide/tree/setup/initial-files/cert

**Comment by lordfido** [comment]
If you mean, private keys and stuff, This is just for develpment server :)

**Comment by Sandalot** [comment]
Yeah I was talking about the keys.
You know see keys and start to think it's the end of the world, sorry for the misunderstanding.

**Comment by lordfido** [comment]
No prob, thanks anyways :)
